index:
    path: /
    controller: App\Controller\AccueilController::index

accueil:
   path: /accueil
   controller: App\Controller\AccueilController::index

connexion:
    path: /connexion
    controller: App\Controller\AccueilController::connexion
