index:
    path: /
    controller: App\Controller\AccueilController::index

<<<<<<< HEAD
accueil:
   path: /accueil
   controller: App\Controller\AccueilController::index

connexion:
    path: /connexion
    controller: App\Controller\AccueilController::connexion
=======
connexion:
   path: /connexion
   controller: App\Controller\AccueilController::connexion
>>>>>>> suty
