<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJbdU9oZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJbdU9oZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJbdU9oZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJbdU9oZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJbdU9oZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JbdU9oZ',
    'container.build_id' => '7d1017bd',
    'container.build_time' => 1543663632,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJbdU9oZ');
