<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfyVmXR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfyVmXR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQfyVmXR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQfyVmXR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQfyVmXR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QfyVmXR',
    'container.build_id' => '12854abe',
    'container.build_time' => 1545303820,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfyVmXR');
