<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLf2d57S\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLf2d57S/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLf2d57S.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLf2d57S\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLf2d57S\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Lf2d57S',
    'container.build_id' => '0ed347bc',
    'container.build_time' => 1542633789,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLf2d57S');
