<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZfwYDa\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZfwYDa/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQZfwYDa.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQZfwYDa\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQZfwYDa\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QZfwYDa',
    'container.build_id' => 'a05ded43',
    'container.build_time' => 1542620958,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZfwYDa');
